name: .NET Publish

on:
  push:
    branches: [ unmined ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build and Pack
        run: dotnet build DialogHost.Avalonia --configuration Release
      - name: Publish to GitHub Packages
        run: dotnet nuget push "DialogHost.Avalonia/bin/Release/*.nupkg" -k ${NUGET_AUTH_TOKEN} --source https://nuget.pkg.github.com/unminednet/index.json --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
